services:

  backend:
    build: ./backend
    container_name: gemini_vosk_backend
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "8765:8765"
      - "2700:2700"
      - "8008:8008"
    volumes:
      - ./backend/models:/app/models
      - ./recordings:/recordings
    # devices:
    #   - "/dev/snd:/dev/snd"
    # group_add:
    #   - audio
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: node-website
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
      - postgresql

  # react-website:
  #   build: ./react-website
  #   container_name: react-website
  #   ports:
  #     - "3000:3000"
  #   restart: always


  postgresql:
    image: postgres:13-alpine3.21
    container_name: postgresql
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catgpt
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: